# Top level data directory. Here we assume the format of the directory conforms
#   to the ImageFolder structure
data_dir:
            - ./data/hymenoptera_data
# Models to choose from [resnet, alexnet, vgg, squeezenet, densenet, inception]
model_names:
            - alexnet
            - vgg
            - resnet
            - squeezenet
            - densenet
            - inception

# Number of classes in the dataset 
num_classes: 2
# Batch size for training (change depending on how much memory you have)
batch_size: 8
# Number of epochs to train format
num_epochs: 15
# Flag for feature extracting. When False, we finetune the whole model,
#   when True we only update the reshaped layer params
feature_extract: True

phase: test

# mysql:
    # host: localhost
    # user: root
    # passwd: my secret password
    # db: write-math
# other:
    # preprocessing_queue:
        # - preprocessing.scale_and_center
        # - preprocessing.dot_reduction
        # - preprocessing.connect_lines
    # use_anonymous: yes